#!/bin/bash

# Solicita ao usuário que selecione uma opção
echo "Selecione a opção desejada:"
echo "1 - Main"
echo "2 - Baesa"
echo ""
read opcao


# Verifica a opção escolhida e executa o arquivo correspondente
if [ "$opcao" == "1" ]; then
    logs=~/projetos/ipt-latex/boletim/main/
    tabela=~/projetos/ipt-latex/boletim/main/python/tabela_main.py
    mapa=~/projetos/ipt-latex/boletim/main/python/mapa_main.py
    input_tex=~/projetos/ipt-latex/boletim/main/main_boletim.tex
    capa=~/projetos/ipt-latex/boletim/main/python/capa.py
    # Verifica se o arquivo existe antes de executá-lo
    echo "Selecione a opção desejada:"
    echo "1 - Machadinho"
    echo "2 - Itá"
    echo "3 - Salto Pilão"
    echo ""
    read opcao2

    # ---------   RELATÓRIO DE MACHADINHO    -----------------------------------------------------------------------------
    if [ "$opcao2" == "1" ];then
        echo " Script Machadinho"
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            echo "Executando "$capa""
            python3 "$capa" 1
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -jobname=Boletim_Machadinho "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Primeiro print"
            pdflatex -jobname=Boletim_Machadinho "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f *.aux *.log *.out *.xmpi *.toc
            echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi

    # -------------   RELATÓRIO DE ITÁ   ----------------------------------------------------------------------------------
    elif [ "$opcao2" == "2" ];then
        echo " Script Itá"
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            echo "Executando "$capa""
            python3 "$capa" 2
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -jobname=Boletim_Itá "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Primeiro print"
            pdflatex -jobname=Boletim_Itá "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f *.aux *.log *.out *.xmpi *.toc
            echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi
        # ---------   RELATÓRIO DE SALTO PILÃO    -----------------------------------------------------------------------------
    elif [ "$opcao2" == "3" ];then
        echo " Script Salto Pilão"
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            echo "Executando "$capa""
            python3 "$capa" 3
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -jobname=Boletim_Salto_Pilão "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Primeiro print"
            pdflatex -jobname=Boletim_Salto_Pilão "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f *.aux *.log *.out *.xmpi *.toc
            echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi
    # ERRO NA ESCOLHA DE OPÇÃO RETORNANDO OPÇÃO INVÁLIDA
    else
        echo "Opção 2 inválida"
        exit 1
    fi

# ---------------- TEMPLATE BAESA -------------------------------------------------------------------------------------
elif [ "$opcao" == "2" ]; then
input_tex=~/projetos/ipt-latex/boletim/baesa/baesa_boletim.tex
logs=~/projetos/ipt-latex/boletim/baesa/
tabela=~/projetos/ipt-latex/boletim/baesa/python/tabela_baesa.py
mapa=~/projetos/ipt-latex/boletim/baesa/python/mapa_baesa.py
completude=~/projetos/ipt-latex/boletim/baesa/python/completude_baesa.py
    if [ -f "$input_tex" ] && [ -f "$tabela" ] && [ -f "$mapa" ] && [ -f "$completude" ];then
        echo "Executando $tabela"
        python3 "$tabela"
        echo "Executando $mapa"
        python3 "$mapa"
        echo "Executando $completude"
        python3 "$completude"
        
        # Gera o arquivo PDF a partir do arquivo LaTeX
        pdflatex -jobname=Boletim_Baesa "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "Primeiro print"
        pdflatex -jobname=Boletim_Baesa "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "Segundo print"
        echo " "

        # Remove arquivos temporários gerados pelo pdflatex
        rm -f *.aux *.log *.out *.xmpi *.toc

        echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"
    else
        echo "Script "$input_tex" não encontrado"
        exit 1
    fi
# --------------------- ERRO NA ESCOLHA DE OPÇÃO RETORNANDO OPÇÃO INVÁLIDA --------------------------------------------
else
    echo "Opção 1 inválida!"
    exit 1
fi
