#!/bin/bash

# Solicita ao usuário que selecione uma opção
echo "Selecione o documento desejado:"
echo "1 - Modelo Principal"
echo "2 - Baesa"
echo "3 - Relatório Técnico"
echo ""
read opcao


# Verifica a opção escolhida e executa o arquivo correspondente
if [ "$opcao" == "1" ]; then
     # Verifica se o arquivo existe antes de executá-lo
    echo "Selecione o Reservatório Desejado:"
    echo "1 - Itá"
    echo "2 - Machadinho"
    echo "3 - Salto Pilão"
    echo ""
    read opcao2

    # ---------   RELATÓRIO DE MACHADINHO    -----------------------------------------------------------------------------
    if [ "$opcao2" == "1" ];then
        logs=~/projetos/ipt-latex/boletim/ita/logs/
        tabela=~/projetos/ipt-latex/boletim/ita/python/tabela_ita.py
        mapa=~/projetos/ipt-latex/boletim/ita/python/mapa_ita.py
        input_tex=~/projetos/ipt-latex/boletim/ita/ita_boletim.tex
        # capa=~/projetos/ipt-latex/boletim/main/python/capa.py
        echo " Modelo Itá Selecionado"
        echo " "
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            # echo "Executando "$capa""
            # python3 "$capa" 1
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo ""
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Itá "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo " -> Primeiro print"
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Itá "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo " -> Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f ./final_boletins/*.aux ./final_boletins/*.log ./final_boletins/*.out ./final_boletins/*.xmpi *./final_boletins/.toc
            echo "Arquivo PDF gerado"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi

    # -------------   RELATÓRIO DE ITÁ   ----------------------------------------------------------------------------------
    elif [ "$opcao2" == "2" ];then
        logs=~/projetos/ipt-latex/boletim/machadinho/logs/
        tabela=~/projetos/ipt-latex/boletim/machadinho/python/tabela_machadinho.py
        mapa=~/projetos/ipt-latex/boletim/machadinho/python/mapa_machadinho.py
        input_tex=~/projetos/ipt-latex/boletim/machadinho/machadinho_boletim.tex
        # capa=~/projetos/ipt-latex/boletim/main/python/capa.py
        echo " Modelo Machadinho Selecionado"
        echo ""
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            # echo "Executando "$capa""
            # python3 "$capa" 2
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
            echo ""
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Machadinho "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "-> Primeiro print"
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Machadinho "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "-> Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f ./final_boletins/*.aux ./final_boletins/*.log ./final_boletins/*.out ./final_boletins/*.xmpi *./final_boletins/.toc
            echo "Arquivo PDF gerado"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi
        # ---------   RELATÓRIO DE SALTO PILÃO    -----------------------------------------------------------------------------
    elif [ "$opcao2" == "3" ];then
        logs=~/projetos/ipt-latex/boletim/salto_pilao/logs/
        tabela=~/projetos/ipt-latex/boletim/salto_pilao/python/tabela_salto.py
        mapa=~/projetos/ipt-latex/boletim/salto_pilao/python/mapa_salto.py
        input_tex=~/projetos/ipt-latex/boletim/salto_pilao/salto_pilao_boletim.tex
        # capa=~/projetos/ipt-latex/boletim/main/python/capa.py
        echo " Modelo Salto Pilão Selecionado"
        echo ""
        if [ -f "$tabela" ] && [ -f "$mapa" ];then
            echo " ---> Iniciando Python scripts"
            # echo "Executando "$capa""
            # python3 "$capa" 3
            echo "Executando $tabela"
            python3 "$tabela"
            echo "Executando $mapa"
            python3 "$mapa"
            echo ""
        else
            echo ""$tabela" e "$mapa""
            echo "Script python não encontrado"
            exit 1
        fi
        
        if [ -f "$input_tex" ]; then 
            # Gera o arquivo PDF a partir do arquivo LaTeX
            echo " ---> Iniciando pdflatex "$input_tex""
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Salto_Pilão "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "-> Primeiro print"
            pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Salto_Pilão "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
            echo "-> Segundo print"
            echo " "
            # Remove arquivos temporários gerados pelo pdflatex
            rm -f ./final_boletins/*.aux ./final_boletins/*.log ./final_boletins/*.out ./final_boletins/*.xmpi *./final_boletins/.toc
            echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"

        else
            echo "Script "$input_tex"  não encontrado"
            exit 1
        fi
    # ERRO NA ESCOLHA DE OPÇÃO RETORNANDO OPÇÃO INVÁLIDA
    else
        echo "Opção '$opcao2' inválida"
        exit 1
    fi

# ---------------- TEMPLATE BAESA -------------------------------------------------------------------------------------
elif [ "$opcao" == "2" ]; then
input_tex=~/projetos/ipt-latex/boletim/baesa/baesa_boletim.tex
logs=~/projetos/ipt-latex/boletim/baesa/logs/
tabela=~/projetos/ipt-latex/boletim/baesa/python/tabela_baesa.py
mapa=~/projetos/ipt-latex/boletim/baesa/python/mapa_baesa.py
completude=~/projetos/ipt-latex/boletim/baesa/python/completude_baesa.py
    if [ -f "$input_tex" ] && [ -f "$tabela" ] && [ -f "$mapa" ] && [ -f "$completude" ];then
        echo " Modelo Baesa Selecionado"
        echo ""
        echo "Executando $tabela"
        python3 "$tabela"
        echo "Executando $mapa"
        python3 "$mapa"
        echo "Executando $completude"
        python3 "$completude"
        echo ""
        
        # Gera o arquivo PDF a partir do arquivo LaTeX
        echo "---> Iniciando pdflatex "$input_tex""
        pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Baesa "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "-> Primeiro print"
        pdflatex -output-directory=./final_boletins/ -jobname=Boletim_Baesa "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "-> Segundo print"
        echo " "

        # Remove arquivos temporários gerados pelo pdflatex
        rm -f ./final_boletins/*.aux ./final_boletins/*.log ./final_boletins/*.out ./final_boletins/*.xmpi *./final_boletins/.toc

        echo "Arquivo PDF gerado: ${input_tex%.tex}.pdf"
    else
        echo "Script "$input_tex" não encontrado"
        exit 1
    fi

# ---------------- TEMPLATE BAESA -------------------------------------------------------------------------------------
elif [ "$opcao" == "3" ]; then
input_tex=~/projetos/ipt-latex/relatorio/relatórios_tecnicos.tex
logs=~/projetos/ipt-latex/relatorio/logs/
tabela=~/projetos/ipt-latex/relatorio/python/tabela.py
mapa=~/projetos/ipt-latex/relatorio/python/mapa.py
regional=~/projetos/ipt-latex/relatorio/python/regional.py
completude=~/projetos/ipt-latex/relatorio/python/completude.py
 
    if [ -f "$input_tex" ] && [ -f "$completude" ] && [ -f "$mapa" ] && [ -f "$regional" ] && [ -f "$tabela" ];then
        echo " ---> Iniciando Python scripts"
        echo "Executando $tablea"
        python3 "$tabela"
        echo "Executando $mapa"
        python3 "$mapa"
        echo "Executando $completude"
        python3 "$completude"
        echo "Executando $regional"
        python3 "$regional"
        echo ""
        
        # Gera o arquivo PDF a partir do arquivo LaTeX
        echo " ---> Iniciando pdflatex"
        pdflatex -output-directory=./final_boletins/ -jobname=Relatóiro_Técnico "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "-> Primeiro print"
        pdflatex -output-directory=./final_boletins/ -jobname=Relatóiro_Técnico "$input_tex" > ""$logs"log_normal.txt" 2> ""$logs"log_erros.txt" 
        echo "-> Segundo print"
        echo " "

        # Remove arquivos temporários gerados pelo pdflatex
        rm -f ./final_boletins/*.aux ./final_boletins/*.log ./final_boletins/*.out ./final_boletins/*.xmpi *./final_boletins/.toc

        echo "Arquivo PDF gerado."
    else
        echo "Script "$input_tex" não encontrado"
        exit 1
    fi
# --------------------- ERRO NA ESCOLHA DE OPÇÃO RETORNANDO OPÇÃO INVÁLIDA --------------------------------------------
else
    echo "Opção '$opcao' inválida!"
    exit 1
fi
